### ISSUE TITLE
Stopping daemon fails with AttributeError

### ISSUE THREAD

**Issue by leforestier** [kevinconway/daemons#14]
On python 3, stopping the daemon raises an AttributeError (the simple daemon example on https://pypi.python.org/pypi/daemons will produce the error).

    Traceback (most recent call last):
      File "/home/username/mydaemon.py", line 33, in <module>
        d.stop()
      File "/home/username/.local/lib/python3.5/site-packages/daemons/startstop/simple.py", line 81, in stop
        if "an integer is required" in err.message:
    AttributeError: 'TypeError' object has no attribute 'message'

This is because `Exception` instances in python3 don't have the `message` attribute. It should probably be replaced with `str(err)`.

**Comment by kevinconway** [comment]
You are right. The `.message` attribute has been deprecated for some time and I shouldn't have used it.

If you want to make a pull request to switch uses of `exc..message` to `str(exc)` in the startstop/simple.py I will gladly merge it.

**Comment by leforestier** [comment]
Done. Thanks for this very handy library by the way!

**Comment by kevinconway** [comment]
Hey, thanks for using the library and thanks even more for putting in both a bug report _and_ a patch. :+1: 

The fact you hit this issue shows I've left some serious test coverage gaps. I'll add reviewing and adding to the tests to my queue. In the meantime, let me know if you hit anything else.

**Comment by kevinconway** [comment]
Also, I forgot to mention. Your change is published to PyPi under version 1.2.2.
